name: Kode workflow

on: push

jobs: 
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: Welcome message
              run: echo "My Kode GitHub Action job."

            - name: List files
              run: ls 

            - name: Read files
               run: cat README.md